site_name: "Crew Docs"
theme: readthedocs
pages:
  - Home: index.md
  - API:
    - Getting Started: crew-api/Index.md
    - Authentication: crew-api/Authentication.md
    - Endpiints:
      - View Network: crew-api/networks/View.md
      - List Projects: crew-api/networks/projects/Index.md
