site_name: "Crew Docs"
theme: readthedocs
pages:
  - Home: index.md
  - API:
    - Getting Started: crew-api/Index.md
    - Authentication: crew-api/Authentication.md
    - Pagination: crew-api/Pagination.md
    - Responses: crew-api/Responses.md
    - Versioning: crew-api/Versioning.md
    - Resources:
      - Networks:
        - crew-api/networks/Index.md
        - View Networks: crew-api/networks/View.md
        - List Projects: crew-api/networks/projects/List.md
